name: Atualizar Skills

on:
  push:
    branches: [ main, master ]  # Vai rodar quando você der push
  workflow_dispatch:            # Permite rodar manualmente também

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: pip install PyGithub
          
      - name: Atualizar skills no README
        run: python .github/scripts/update_skills.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit as mudanças
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Skills atualizadas automaticamente"
          git push